### ISSUE TITLE
Test fails with python 3.4

### ISSUE THREAD

**Issue by hobbes1069** [pycollada/pycollada#39]
Here's the output of the test:
```/usr/bin/python3 setup.py test
running test
running egg_info
writing top-level names to pycollada.egg-info/top_level.txt
writing pycollada.egg-info/PKG-INFO
writing requirements to pycollada.egg-info/requires.txt
writing dependency_links to pycollada.egg-info/dependency_links.txt
reading manifest file 'pycollada.egg-info/SOURCES.txt'
writing manifest file 'pycollada.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    packages = find_packages()
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/builddir/build/BUILD/python3-python-collada-0.4-6.fc22/collada/__init__.py", line 30, in <module>
    from collada import animation
ImportError: cannot import name 'animation'```

**Comment by hobbes1069** [comment]
Ok, I'm sorry to say I completely forgot about this bug I went ahead and tried another build to see if anything has changed. I don't see any reference to 'six' anymore but one test still failed with Python 3.
```
ERROR: test_geometry_triangleset_adding (collada.tests.test_geometry.TestGeometry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/tests/test_geometry.py", line 97, in test_geometry_triangleset_adding
    loaded_triangleset = collada.triangleset.TriangleSet.load(self.dummy, geometry.sourceById, fromstring(tostring(triangleset.xmlnode)))
  File "/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/triangleset.py", line 200, in load
    source_array = primitive.Primitive._getInputs(collada, localscope, node.findall(tag('input')))
  File "/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/primitive.py", line 171, in _getInputs
    return Primitive._getInputsFromList(collada, localscope, inputs)
  File "/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/primitive.py", line 124, in _getInputsFromList
    raise DaeBrokenRefError('Source input id "%s" not found' % source)
collada.common.DaeBrokenRefError: DaeBrokenRefError: Source input id "#cubeverts-array-vertices" not found
```
On a side note I also saw this:
```
test_cimage_data_loading (collada.tests.test_material.TestMaterial) ... /builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/tests/test_material.py:107: DeprecationWarning: Please use assertTrue instead.
  self.failUnless(os.path.isfile(texture_file_path), "Could not find data/duckCM.tga file for testing")
/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/tests/test_material.py:109: ResourceWarning: unclosed file <_io.BufferedReader name='/builddir/build/BUILD/python3-python-collada-0.4-7.fc21/collada/tests/data/duckCM.tga'>
  texdata = open(texture_file_path, 'rb').read()
ok
```

**Comment by jterrace** [comment]
The failUnless is an easy fix.

The DaeBrokenRefError I haven't been able to track down. It only fails sometimes, not always, so it's a strange bug. It also only happens on 3.x.

**Comment by hobbes1069** [comment]
Is there an easy way to skip this test? Or better, only skip it for python3?

**Comment by jterrace** [comment]
Yeah, we could mark it as broken for now with the unittest @skip decorator. I think it actually *is* some sort of bug though.

**Comment by hobbes1069** [comment]
Ok, for now I just kicked off another build and it completed this time so I'm OK until a new release or rebuild.
