### ISSUE TITLE
ERROR: test_geometry_triangleset_adding (collada.tests.test_geometry.TestGeometry)

### ISSUE THREAD

**Issue by hobbes1069** [pycollada/pycollada#61]
While doing a mass rebuild for GCC 7 on Fedora Rawhide the following test failed:

```
ERROR: test_geometry_triangleset_adding (collada.tests.test_geometry.TestGeometry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-collada-0.4-14.fc26/collada/tests/test_geometry.py", line 97, in test_geometry_triangleset_adding
    loaded_triangleset = collada.triangleset.TriangleSet.load(self.dummy, geometry.sourceById, fromstring(tostring(triangleset.xmlnode)))
  File "/builddir/build/BUILD/python3-python-collada-0.4-14.fc26/collada/triangleset.py", line 200, in load
    source_array = primitive.Primitive._getInputs(collada, localscope, node.findall(tag('input')))
  File "/builddir/build/BUILD/python3-python-collada-0.4-14.fc26/collada/primitive.py", line 171, in _getInputs
    return Primitive._getInputsFromList(collada, localscope, inputs)
  File "/builddir/build/BUILD/python3-python-collada-0.4-14.fc26/collada/primitive.py", line 124, in _getInputsFromList
    raise DaeBrokenRefError('Source input id "%s" not found' % source)
collada.common.DaeBrokenRefError: DaeBrokenRefError: Source input id "#cubeverts-array-vertices" not found
----------------------------------------------------------------------```

**Comment by jterrace** [comment]
I've seen this flake a lot. It seems to be more common in python 3.

**Comment by hobbes1069** [comment]
Do we know if it's a real failure or just the test itself not being python3 compatible?

**Comment by jterrace** [comment]
Not really sure honestly. I've spent some time multiple times trying to root cause the flake, and I haven't been able to figure out what the root cause is.

**Comment by hobbes1069** [comment]
Well, this is sitting FTBFS on Fedora Rawhide. I think for now I'll just skip the tests for the python 3 package. Not ideal though...
