### ISSUE TITLE
<type 'exceptions.ValueError'> on a collada file

### ISSUE THREAD

**Issue by sylvestre** [pycollada/pycollada#84]
Trying to load in freecad the following file: https://3dwarehouse.sketchup.com/model/06313964-7555-4f9a-8097-bb1dbc459d35/GARBAGE-BIN-SHED

Fails with 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/freecad/Mod/Arch/importDAE.py", line 78, in open
    read(filename)
  File "/usr/lib/freecad/Mod/Arch/importDAE.py", line 111, in read
    for geom in col.scene.objects('geometry'):
  File "/usr/lib/python2.7/dist-packages/collada/scene.py", line 897, in objects
    for obj in node.objects(tipo, matrix): yield obj
  File "/usr/lib/python2.7/dist-packages/collada/scene.py", line 374, in objects
    for obj in node.objects(tipo, M):
  File "/usr/lib/python2.7/dist-packages/collada/scene.py", line 371, in objects
    if not matrix is None: M = numpy.dot( matrix, self.matrix )
<type 'exceptions.ValueError'>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
[model.dae.gz](https://github.com/pycollada/pycollada/files/2152794/model.dae.gz)

**Comment by sylvestre** [comment]
Importing the file with SketchUp, this tool detected an issue in the file, proposed to fix it. The file can be imported later in pycollada.

**Comment by jterrace** [comment]
I can't reproduce this:

```
>>> c = collada.Collada("/Users/jterrace/Downloads/Rib Test.dae")
>>> list(c.scene.objects('geometry'))
[<BoundGeometry id=ID3, 1 primitives>]
```
